// Commit generated routes and metadata together; --check is entirely offline.
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');
const site = 'https://modemode.studio';
const meta = JSON.parse(await readFile(path.join(root, 'data/site-meta.json'), 'utf8'));
const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugs = (await readdir(path.join(root, 'content')))
  .filter(f => f.endsWith('.json')).map(f => f.slice(0, -5)).sort();
const nav = '<nav aria-label="Project index"><ul>' + slugs.map(s => `<li><a href="${site}/${s}">${esc(meta[s]?.name || s)}</a></li>`).join('') + '</ul></nav>';
function metadata(slug){
  const m = meta[slug];
  if (!m?.title || !m.description || !m.image || !m.imageAlt) throw Error('Missing metadata: ' + slug);
  if (m.description.length > 160) throw Error('Keep the description brief: ' + slug);
  const url = site + (slug === 'home' ? '/' : '/' + slug), img = new URL(m.image, site + '/').href;
  return `<!-- mm-meta:start -->
<title>${esc(m.title)}</title>
<meta name="description" content="${esc(m.description)}">
<link rel="canonical" href="${url}">
<meta property="og:type" content="website">
<meta property="og:site_name" content="MODE MODE">
<meta property="og:title" content="${esc(m.title)}">
<meta property="og:description" content="${esc(m.description)}">
<meta property="og:url" content="${url}">
<meta property="og:image" content="${esc(img)}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="${esc(m.imageAlt)}">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${esc(m.title)}">
<meta name="twitter:description" content="${esc(m.description)}">
<meta name="twitter:image" content="${esc(img)}">
<meta name="twitter:image:alt" content="${esc(m.imageAlt)}">
<!-- mm-meta:end -->`;
}
function stamp(html, slug){
  return html.replace(/<!-- mm-meta:start -->[\s\S]*?<!-- mm-meta:end -->|<title>[\s\S]*?<\/title>/, metadata(slug));
}
function fallback(slug){
  const m = meta[slug];
  return `<!-- mm-content:start --><section class="page-fallback"><a href="${site}/">MODE MODE</a><h1>${esc(m.name)}</h1><p>${esc(m.description)}</p>${nav}<p><a href="mailto:hello@modemode.studio">Get in touch — hello@modemode.studio</a></p></section><!-- mm-content:end -->`;
}
async function output(file, html){
  const dest = path.join(root, file);
  if (check) {
    const actual = (await readFile(dest, 'utf8').catch(() => '')).replace(/\r\n/g, '\n');
    if (actual !== html) throw Error('Stale generated file: ' + file);
  } else { await mkdir(path.dirname(dest), {recursive:true}); await writeFile(dest, html); }
}
let home = (await readFile(path.join(root, 'index.html'), 'utf8')).replace(/\r\n/g, '\n');
home = stamp(home, 'home').replace(/<!-- mm-content:start -->[\s\S]*?<!-- mm-content:end -->/, fallback('home'));
await output('index.html', home);
let about = (await readFile(path.join(root, 'about.html'), 'utf8')).replace(/\r\n/g, '\n');
about = stamp(about, 'about');
const c = meta.about.copy;
const copy = `<div class="kicker">${esc(c.kicker)}</div><h1 class="lede">${esc(c.lede)}</h1><div class="body">${c.body.split(/\n{2,}/).map(p=>'<p>'+esc(p).replace(/\n/g,'<br>')+'</p>').join('')}</div><p class="contact"><a href="mailto:hello@modemode.studio">Get in touch — hello@modemode.studio</a></p><div class="meta">${esc(c.meta).replace(/\n/g,'<br>')}</div>`;
about = about.replace(/<!-- mm-about:start -->[\s\S]*?<!-- mm-about:end -->/, '<!-- mm-about:start -->'+copy+'<!-- mm-about:end -->');
await output('about.html', about);
for (const slug of slugs) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw Error('Invalid route: ' + slug);
  const page = slug === 'about' ? 'about' : 'project';
  let html = page === 'about' ? about : (await readFile(path.join(root, 'project.html'), 'utf8')).replace(/\r\n/g, '\n');
  html = stamp(html, slug).replace('<head>', '<head>\n<!-- Generated by scripts/build-routes.mjs; edit ' + page + '.html and data/site-meta.json. -->\n<base href="../">')
    .replace('data-mm-page="' + page + '"', 'data-mm-page="' + page + '" data-mm-slug="' + slug + '"');
  if (page === 'project') html = html.replace('<!-- rendered by JS -->', fallback(slug)).replace('<meta name="robots" content="noindex,follow">', '');
  await output(slug + '/index.html', html);
}
await output('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + ['home',...slugs].map(s=>'  <url><loc>'+site+(s==='home'?'/':'/'+s)+'</loc></url>').join('\n') + '\n</urlset>\n');
await output('robots.txt', 'User-agent: *\nAllow: /\n\nSitemap: '+site+'/sitemap.xml\n');
console.log((check ? 'Checked' : 'Generated') + ' ' + slugs.length + ' routes, page metadata, and sitemap.');
