// No build service or dependencies: commit these generated routes with source edits.
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = fileURLToPath(new URL('../', import.meta.url));
const check = process.argv.includes('--check');
const slugs = (await readdir(path.join(root, 'content')))
  .filter(f => f.endsWith('.json')).map(f => f.slice(0, -5));
for (const slug of slugs) {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw Error('Invalid route: ' + slug);
  const page = slug === 'about' ? 'about' : 'project';
  let html = await readFile(path.join(root, page + '.html'), 'utf8');
  html = html.replace('<head>', '<head>\n<!-- Generated by scripts/build-routes.mjs; edit ' + page + '.html. -->\n<base href="../">')
    .replace('data-mm-page="' + page + '"', 'data-mm-page="' + page + '" data-mm-slug="' + slug + '"');
  const dest = path.join(root, slug, 'index.html');
  if (check) {
    if (await readFile(dest, 'utf8').catch(() => '') !== html) throw Error('Stale route: ' + slug);
  } else {
    await mkdir(path.dirname(dest), { recursive: true });
    await writeFile(dest, html);
  }
}
console.log((check ? 'Checked' : 'Generated') + ' ' + slugs.length + ' static routes.');
